### ISSUE TITLE
uuid import module error

### ISSUE THREAD

**Issue by chrisdavenport** [jbesw/sar-s3-serverless-uploader#2]
I followed the video tutorial, but I'm getting this error:

"errorType": "Runtime.ImportModuleError",
"errorMessage": "Error: Cannot find module 'uuid/v4'\nRequire stack:\n- /var/task/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/index.js"

I'm not a Node or JS developer, so I'm not sure how to fix it.

**Comment by jbesw** [comment]
Hi Chris! Typically, this happens if you don't run `sam build` before `sam deploy`. The build command installs the packages in the package.json file before the function is deployed. Try running `sam build` first and let me know how it goes! Also, feel free to DM me on Twitter @jbesw if you continue to have issues.

**Comment by jbesw** [comment]
Actually, I just modified the code to remove the dependency on UUID since it's not needed for this demo. This means you do not need to package anything to run this example, which hopefully makes it easier. Please try again with the new version of app.js.

**Comment by chrisdavenport** [comment]
Oh that's much better, it works now!  Thank you so much.

**Comment by jbesw** [comment]
Anytime!
